#!/usr/bin/env php
<?php

/**
 * PHP CLI Excutable file. Outputs the required WordPress keys and salts in
 * either the traditional WordPress define format or the Composer driven
 * DotEnv format.
 *
 * When loaded via composer this file can be executed in CLI as follows:
 * vendor/bin/wpsalts
 *
 * @author Rob Waller <rdwaller1984@googlemail.com>
 */


/**
 * Load the correct autoloader dependent on how this file is being executed.
 */
$paths = [
    __DIR__.'/vendor/autoload.php',
    __DIR__.'/../../autoload.php'
];

foreach ($paths as $path) {
    if (file_exists($path)) {
        require_once $path;
        break;
    }
}

/**
 * Load the WordPress salts class
 */
$salts = new WPSalts\Salts;

/**
 * Return the WordPress salts in a DotEnv format for use in .env files.
 */
if ($argv[1] === 'dotenv') {
    echo "\33[33mCopy and paste these keys and salts into your \33[32m.env\33[33m file.\33[0m" . PHP_EOL . PHP_EOL;
    echo "\33[32m" . $salts->dotEnv() . "\33[0m";
    die();
}

/**
 * Return the WordPress salts in the traditional WordPress define format for
 * use in wp-config.php files.
 */
if ($argv[1] === 'traditional') {
    echo "\33[33mCopy and paste these keys and salts into your \33[32mwp-config.php\33[33m file.\33[0m" . PHP_EOL . PHP_EOL;
    echo "\33[32m" . $salts->traditional() . "\33[0m";
    die();
}

/**
 * By default this script will return the WordPress salts in the traditioanl
 * define format.
 */
echo "\33[33mCopy and paste these keys and salts into your \33[32mwp-config.php\33[33m file.\33[0m" . PHP_EOL . PHP_EOL;
echo "\33[32m" . $salts->traditional() . "\33[0m";
die();
